import { z } from 'zod';

export enum AnnotationDateTimeFormat {
  DMYNUMERICSLASH = 'DMY_NUMERIC_SLASH',
  MDYNUMERICSLASH = 'MDY_NUMERIC_SLASH',
  YMDNUMERICSLASH = 'YMD_NUMERIC_SLASH',
  DMYNUMERICDASHSHORT = 'DMY_NUMERIC_DASH_SHORT',
  DMYNUMERICDASH = 'DMY_NUMERIC_DASH',
  YMDNUMERICDASH = 'YMD_NUMERIC_DASH',
  MDYTEXTDASHSHORT = 'MDY_TEXT_DASH_SHORT',
  MDYTEXTSPACESHORT = 'MDY_TEXT_SPACE_SHORT',
  MDYTEXTSPACE = 'MDY_TEXT_SPACE',
}
