import { z } from 'zod';

export enum AnnotationDateTimeFormat {
  DMY_NUMERIC_SLASH = 'DMY_NUMERIC_SLASH',
  MDY_NUMERIC_SLASH = 'MDY_NUMERIC_SLASH',
  YMD_NUMERIC_SLASH = 'YMD_NUMERIC_SLASH',
  DMY_NUMERIC_DASH_SHORT = 'DMY_NUMERIC_DASH_SHORT',
  DMY_NUMERIC_DASH = 'DMY_NUMERIC_DASH',
  YMD_NUMERIC_DASH = 'YMD_NUMERIC_DASH',
  MDY_TEXT_DASH_SHORT = 'MDY_TEXT_DASH_SHORT',
  MDY_TEXT_SPACE_SHORT = 'MDY_TEXT_SPACE_SHORT',
  MDY_TEXT_SPACE = 'MDY_TEXT_SPACE',
}
