import { z } from 'zod';

export enum EnvelopeOrderField {
  CREATION_DATE = 'CREATION_DATE',
  MODIFICATION_DATE = 'MODIFICATION_DATE',
  NAME = 'NAME',
  STATUS = 'STATUS',
  LAST_DOCUMENT_CHANGE = 'LAST_DOCUMENT_CHANGE',
}
