import { z } from 'zod';

export enum TemplateOrderField {
  TEMPLATEID = 'TEMPLATE_ID',
  TEMPLATECREATIONDATE = 'TEMPLATE_CREATION_DATE',
  TEMPLATEMODIFICATIONDATE = 'TEMPLATE_MODIFICATION_DATE',
  TEMPLATENAME = 'TEMPLATE_NAME',
}
