import { z } from 'zod';

export enum TemplateOrderField {
  TEMPLATE_ID = 'TEMPLATE_ID',
  TEMPLATE_CREATION_DATE = 'TEMPLATE_CREATION_DATE',
  TEMPLATE_MODIFICATION_DATE = 'TEMPLATE_MODIFICATION_DATE',
  TEMPLATE_NAME = 'TEMPLATE_NAME',
}
