import { z } from 'zod';

export enum WebhookEvent {
  ENVELOPEEXPIRED = 'ENVELOPE_EXPIRED',
  ENVELOPEDECLINED = 'ENVELOPE_DECLINED',
  ENVELOPEVOIDED = 'ENVELOPE_VOIDED',
  ENVELOPECOMPLETED = 'ENVELOPE_COMPLETED',
}
