import { z } from 'zod';

export enum WebhookEvent {
  ENVELOPE_EXPIRED = 'ENVELOPE_EXPIRED',
  ENVELOPE_DECLINED = 'ENVELOPE_DECLINED',
  ENVELOPE_VOIDED = 'ENVELOPE_VOIDED',
  ENVELOPE_COMPLETED = 'ENVELOPE_COMPLETED',
}
